### ISSUE TITLE
timeline-slider with polygons

### ISSUE THREAD

**Issue by ealoticopve** [svitkin/leaflet-timeline-slider#6]
- Hello my  friend, your plugin its really nice and i am very interested in it. I already integrated into my application but it doesn't work with polygons, is it any way to getting it or this just works to Points? Thank u in advance!!

- Quick example for i want:

I would like different polygons to appear when moving timeline. Very closed to demo but with polygons.

**Comment by svitkin** [comment]
You can customize the function that adds and takes away elements from the map when the timeline changes. To get what you want with the demo example, the main change would be to the geoJSON data so that it contains polygon coordinates. Then just make the `getDataAddMarkers` function create polygon layers from the data and add those instead of markers. Let me know if you have any questions about the details of this approach!

**Comment by ealoticopve** [comment]
Hello!! Good morning, thanks for your reply!

I have tried to follow in your footsteps as indicated. However, I am not getting the expected results, in fact it gives an error in GeoJSON. Here are some screenshots of what's going on:

![0](https://user-images.githubusercontent.com/61938096/82933497-e5030780-9f81-11ea-9009-df10ba82897a.png)

![1](https://user-images.githubusercontent.com/61938096/82933517-eaf8e880-9f81-11ea-841a-4878c4b3a4ca.png)

What can I do to solve this?
Thank you in advance!!

**Comment by svitkin** [comment]
In your GeoJSON, change the type from Point to Polygon

**Comment by ealoticopve** [comment]
![0](https://user-images.githubusercontent.com/61938096/82937564-46c67000-9f88-11ea-92cd-3b8f0616ce23.png)

- [x] Changed to Polygon
- [ ]  New error

**Comment by svitkin** [comment]
I'm not sure, but I think this is an issue with the data and GeoJSON, not the plugin. I recommend just [googling](https://www.google.com/search?q=invalid+latlng+object+(undefined+undefined)+site:stackoverflow.com&client=firefox-b-1-d&sxsrf=ALeKk00mV_aFIC2_nz90udt1xIV_dS-3Rw:1590525195984&sa=X&ved=2ahUKEwjH_b-KsNLpAhXynuAKHaLTAo0QrQIoBDAAegQIAxAN&biw=1176&bih=684) around if you're not sure and messing around with your data and your function until you get something working. Good luck!
