### ISSUE TITLE
Problems using the circleMarker

### ISSUE THREAD

**Issue by gustrava** [svitkin/leaflet-timeline-slider#9]
When I try to use a circleMarker instead of a single Marker (default) and try to change the time in the timeline it return message error as follow:

Uncaught TypeError: Cannot read property 'x' of undefined

and the map isn't updated.

Do you have any example using the timeline with circleMarkers?

Thanks,

**Comment by svitkin** [comment]
Yes, it is possible. For the example in the demo, you just have to modify the function that is being called on each change of the timeline. In general, this `changeMap` is where you would want to put your customizations. Below is an example you can use in the demo to see circleMarkers:
```
getDataAddMarkers = function( {label, value, map, exclamation} ) {
                map.eachLayer(function (layer) {
                    if (layer instanceof L.CircleMarker) {
                        map.removeLayer(layer);
                    }
                });

                filteredData = data.features.filter(function (i, n) {
                    return i.properties.title===label;
                    });

                var fGroup = L.featureGroup();
                var markerArray = [];
                L.geoJSON(filteredData, {
                    pointToLayer: function (feature, latlng) {
                        var marker = L.circleMarker(latlng)
                        marker.addTo(fGroup);
                        return marker;
                    }
                }).addTo(map);
                map.fitBounds(fGroup.getBounds()).setZoom(12);
            };
```
